version: '3.3'

services:
  postgres_service:
    image: postgres:13.9
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"