spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

logging:
  file:
    path: .
  pattern:
    console: "%d{yyyy-M-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    sql: debug

# Server configuration
server:
  port: 8080 #set your port
