server:
  .port=8080

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    path: .
  pattern:
    console: "%d{yyyy-M-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    sql: debug
